### ISSUE TITLE
Mime-type detection too broad

### ISSUE THREAD

**Issue by Caesurus** [fkie-cad/fact_helper_file#17]
https://github.com/fkie-cad/fact_helper_file/blob/master/fact_helper_file/mime/custom_mime_encoding#L12-L15
```
# Tektronik HEX file format
0   string /
>1  regex  [0-9A-F]{8,}$  Tektronix HEX; binary data in text format
!:mime  firmware/tek
```
This is too broad. It will match a bunch of source code files, eg `.c/.h/.js` if they start with `/*` which a LOT of files do with headers.

**Comment by jstucke** [comment]
Sorry for the late response. This somehow totally flew under our radar. Thank you for reporting this. I could confirm the issues. #24 should hopefully fix most issues but since the standard is very generic it is hard to write a regex that it totally free of FPs for this MIME type.

**Comment by rhelmke** [comment]
#24 is merged. Feel free to re-open in case the matching is still toob road
