### ISSUE TITLE
MIME type for firmware with a prepended signature

### ISSUE THREAD

**Issue by soxrok2212** [fkie-cad/fact_helper_file#34]
Hi,

I have a firmware that has an n-byte DER signature prepended to the firmware _before_ the unsigned version's magic bytes. I'm wondering what would be the best route for this problem since the magic bytes exist, but they're just not at the start of the binary and I want to make sure my custom extractor is used over the generic one.

An example firmware (bytes) might look like:
```
3082060D<1549 bytes of data>12345678<rest of the firmware>
```

Where `12345678` are the magic bytes. The DER signature length can be different for any given release.
Cheers!

**Comment by jstucke** [comment]
Hi, you just need to write an entry in any of the magic files with a custom MIME type (see the existing magic rules or a [guide](https://www.ibm.com/docs/en/zos/2.4.0?topic=formats-magic-format-etcmagic-file) on how to do that or ask ChatGPT) and assign this MIME type to your custom unpacker:

```python
MIME_PATTERNS = ['<your/custom/mime>']
```

fact_helper_file is used inside the extractor for determining the file's (MIME) type, so you need to make sure that the version with your MIME type is installed when building the Docker image of the extractor.

**Comment by jstucke** [comment]
Maybe I should add that you can always test if your custom MIME type works by installing fact_helper_file from your local directory (`pip install .`) and checking the type of your firmware file:
```python
from fact_helper_file import get_file_type_from_path
get_file_type_from_path("path/to/your/fw")
```

**Comment by soxrok2212** [comment]
Right, for other devices I've made a few custom entries, but those did not have signatures in the firmwares. I just wasn't sure if the magic had to be at the start of the binary for it to be detected, or if it just had to exist _somewhere_ in the binary.

**Comment by soxrok2212** [comment]
Understood, thank you kindly!
